name: animove_example
description: Demo app for the animove package
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  animove:
    path: ../
  animated_to: ^0.8.1
  # animated_to:
  #   path: /home/mako/programming/colab/animated_to
  hero_animation: ^1.1.4

flutter:
  uses-material-design: true
